name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Make application-secret.properties
        run: |
          cd ./src/main/resources
          touch ./application-secret.properties                                      
          echo "${{ secrets.YML_SECRET }}" > ./application-secret.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Create app directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/app

      - name: Copy JAR and Dockerfile to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./build/libs/*.jar,dockerfile"
          target: "~/app"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/app
            mv dockerfile Dockerfile
            docker stop my-app || true
            docker rm my-app || true
            docker build -t my-app .
            docker run -d --name my-app -p 8080:8080 my-app
